/*
  Create a graph archive set and corresponding stats for METAL
  graph data.

  For each graph set created from the current TM data, compute
  additional stats about existing simple, collapsed, and traveled, and
  create an intersection-only graph from the collapsed and compure its
  stats as well.  The program creates a .sql file (with its name
  matching the archive name specified in argv[1]) with the additions
  to the graphArchive and graphArchiveSets for these graphs.  This
  should be then loaded into the TravelMapping and TravelMappingCopy
  DBs on the TM/METAL server.

  The program expects the environment variables GRAPH_DIR to be the
  path to the graphs generated by TM's site update process that are to
  be included in this archive, and HIGHWAY_DATA to be the path to the
  TravelMapping/HighwayData repository where the list of systems,
  regions, countries, and continents, as well as the custom graphs are
  defined.

  Jim Teresco, Summer 2022
*/

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>

#include "tmggraph.h"

void usage(char *progname) {

  fprintf(stderr, "Usage: %s archive_name description datestr hwy_vers user_vers dataproc_vers write_dir\n", progname);
  exit(1);
}

int main(int argc, char *argv[]) {

  /* check for required command-line parameters:

     argv[1]: name of archive
     argv[2]: longer description of the archive set
     argv[3]: SQL-format date string YYYY-MM-DD
     argv[4]: TravelMapping/HighwayData repository version
     argv[5]: TravelMapping/UserData repository version
     argv[6]: TravelMapping/DataProcessing repository version
     argv[7]: location to write intersection-only graphs and .sql,
              which must be a writable directory
  */
  if (argc != 8) {
    fprintf(stderr, "Error: incorrect number of command-line parameters.\n");
    usage(argv[0]);
  }

  char *archive_name = argv[1];
  char *description = argv[2];
  char *hwy_vers = argv[3];
  char *user_vers = argv[4];
  char *dataproc_vers = argv[5];
  /* should check here for a proper date format */
  char *datestamp = argv[6];
  char *outdir = argv[7];

  /* try to open the directory */
  DIR *d = opendir(outdir);
  if (d == NULL) {
    fprintf(stderr, "Could not open output directory %s\n", outdir);
    usage(argv[0]);
  }
  closedir(d);

  /* check for required environment variables */

  char *graph_dir = getenv("GRAPH_DIR");
  if (graph_dir == NULL) {
    fprintf(stderr, "The GRAPH_DIR environment variable must be set to the location of a current set of graph files.\n");
    exit(1);
  }
  d = opendir(graph_dir);
  if (d == NULL) {
    fprintf(stderr, "Could not open graph file directory %s\n", graph_dir);
    usage(argv[0]);
  }
  closedir(d);

  char *hwy_data = getenv("HIGHWAY_DATA");
  if (hwy_data == NULL) {
    fprintf(stderr, "The HIGHWAY_DATA environment variable must be set to the location of the TravelMapping/HighwayData repository.\n");
    exit(1);
  }
  d = opendir(hwy_data);
  if (d == NULL) {
    fprintf(stderr, "Could not open highway data directory %s\n", hwy_data);
    usage(argv[0]);
  }
  closedir(d);

  /* create the .sql file */
  char sqlfilename[4096];
  sprintf(sqlfilename, "%s/%s.sql", outdir, archive_name);
  FILE *sqlfp = fopen(sqlfilename, "wt");
  if (sqlfp == NULL) {
    fprintf(stderr, "Could not open file %s for writing.\n", sqlfilename);
    perror(NULL);
    exit(1);
  }

  printf("New graph archive set %s (%s) datestamp %s\n", archive_name,
	 description, datestamp);
  printf("Creating graph archive SQL file %s\n", sqlfilename);
  printf("Graphs created by TM siteupdate are in %s\n", graph_dir);
  printf("Graphs based on HighwayData rev %s in %s\n", hwy_vers, hwy_data);
  printf("and UserData rev %s, DataProcessing rev %s\n", user_vers,
	 dataproc_vers);

  fclose(sqlfp);
  
  return 0;
}

